'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const XLSX = require('../assets/xlsx.full.min.js');
const html = fs.readFileSync(path.join(__dirname, '../index.html'), 'utf8');
const context = vm.createContext({});
for (const name of ['buildSkuExcelRows', 'parseExcelExportValue', 'looksLikeExportNumber', 'parseBrazilianNumber']) {
  const start = html.indexOf('    function ' + name + '(');
  const end = html.indexOf('\n    function ', start + 1);
  vm.runInContext(html.slice(start, end), context);
}
assert.equal(context.parseExcelExportValue('R$ 103.146', false).value, 103146);
assert.equal(context.parseExcelExportValue('-R$ 10.016', false).value, -10016);
assert.equal(context.parseExcelExportValue('R$ 1.213.083,57', false).value, 1213083.57);
assert.equal(context.parseExcelExportValue('4%', false).value, 0.04);
assert.equal(context.parseExcelExportValue('+2,50 p.p.', false).value, 2.5);
assert.equal(context.parseExcelExportValue('001195', true).value, '001195');
const details = Array.from({ length: 2069 }, (_, i) => ({ marketplaceSale: 'Magalu', sku: '00' + i, ad: '12345678901234567890', revenue: 103146.25, gm: -10016.50 }));
const result = context.buildSkuExcelRows(details);
assert.equal(result.values.length, 2071);
assert.equal(result.values[0][0], 'Marketplace venda');
assert.equal(result.values[1][1], '000');
assert.equal(result.values[1][3], 103146.25);
assert.equal(result.values.at(-1)[0], 'Total geral');
assert.equal(result.values.at(-1)[3], 2069 * 103146.25);
assert.equal(result.values.at(-1)[4], 2069 * -10016.50);
assert.equal(context.buildSkuExcelRows([]).values.at(-1)[5], 0);
const sheet = XLSX.utils.aoa_to_sheet(result.values);
for (const cell of result.cells) sheet[XLSX.utils.encode_cell({r:cell.row,c:cell.col})].z = cell.format;
const book = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(book, sheet, 'SKU e Anúncio');
const readback = XLSX.read(XLSX.write(book, {type:'buffer',bookType:'xlsx'}), {type:'buffer',cellNF:true}).Sheets['SKU e Anúncio'];
assert.equal(readback['!ref'], 'A1:F2071');
assert.equal(readback.B2.t, 's');
assert.equal(readback.C2.v, '12345678901234567890');
assert.equal(readback.D2.v, 103146.25);
assert.equal(readback.F2.z, '0.00%');
console.log('Excel export tests: PASS (2,069 records, totals, precision and identifier types)');
